In [30]:
import numpy as np
from sklearn.model_selection import KFold
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix


In [21]:
b_c_data=load_breast_cancer()
X,y=load_breast_cancer(return_X_y=True,as_frame=False)
print(X,y)
#print(X.shape)
#print(y.shape)
X_train,X_test,y_train,y_test=train_test_split(X,y,stratify=y,random_state=1)
print(X_train.shape)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

**(i) Use Keras or any other framework to construct a decision tree from the training data and obtain the performance on the test data**

In [33]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
dt_accuracy=0
rf_accuracy=0
dt = tree.DecisionTreeClassifier(random_state=10)
kf = KFold(n_splits=5,shuffle=True,random_state=10)
for k, (train_indices, test_indices) in enumerate(kf.split(X)):
  X_train, X_test = X[train_indices], X[test_indices]
  y_train, y_test = y[train_indices], y[test_indices]
  dt.fit(X[train_indices], y[train_indices])
  dt_accuracy+=dt.score(X[test_indices], y[test_indices])*100
  print(
      "[fold {0}] score: {1:.5f}".format(
          k, dt.score(X[test_indices], y[test_indices])*100)
      )
print('Mean DT accuracy:', dt_accuracy/5)

[fold 0] score: 85.96491
[fold 1] score: 95.61404
[fold 2] score: 91.22807
[fold 3] score: 92.10526
[fold 4] score: 92.03540
Mean DT accuracy: 91.38953578636857


**(ii) Construct a random forest (of say, 100 trees) from the training data and use the random forest to obtain the performance on the test data**

In [37]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=10)
kf = KFold(n_splits=5,shuffle=True,random_state=10)
dt_accuracy=0
rf_accuracy=0
for k, (train_indices, test_indices) in enumerate(kf.split(X)):
  X_train, X_test = X[train_indices], X[test_indices]
  y_train, y_test = y[train_indices], y[test_indices]
  rf.fit(X[train_indices], y[train_indices])
  rf_accuracy+=rf.score(X[test_indices], y[test_indices])*100
  print(
      "[fold {0}] score: {1:.5f}".format(
          k, rf.score(X[test_indices], y[test_indices])*100)
      )
print('Mean RF accuracy:', rf_accuracy/5)

[fold 0] score: 98.24561
[fold 1] score: 98.24561
[fold 2] score: 95.61404
[fold 3] score: 94.73684
[fold 4] score: 92.03540
Mean RF accuracy: 95.77550069864928


**(iii) Compare the performance you obtain in (i) and (ii)**

On comparing the above two models, it is noted that the average accuracy score of Random Forest model is better than the the average accuracy score of Decision Tree model. This can be because of the extra randomness of the Random Forest algorithm with the increase in trees and searches for the best features among all the features. Thus, the algorithm results in greater tree diversity, which trades a higher bias for a lower variance, generally yielding an overall better model.

In [39]:
dt_accuracy=0
rf_accuracy=0
for k, (train_indices, test_indices) in enumerate(kf.split(X)):
  X_train, X_test = X[train_indices], X[test_indices]
  y_train, y_test = y[train_indices], y[test_indices]
  dt.fit(X[train_indices], y[train_indices])
  '''print(
      "[fold {0}] Decision Tree score: {1:.5f}".format(
          k, dt.score(X[test_indices], y[test_indices])*100)
      )'''
  dt_accuracy+=dt.score(X[test_indices], y[test_indices])*100
  rf.fit(X[train_indices], y[train_indices])
  '''print(
      "[fold {0}] Random Forest Classifier score: {1:.5f}".format(
          k, rf.score(X[test_indices], y[test_indices])*100)
      )'''
  rf_accuracy+=rf.score(X[test_indices], y[test_indices])*100
print('Mean DT accuracy:', dt_accuracy/5)
print('Mean RF accuracy:', rf_accuracy/5)

Mean DT accuracy: 91.38953578636857
Mean RF accuracy: 95.77550069864928
